const HNDT_LOGO = [
    {
        url:require('logos/hndt-icon/icon-hndt-01.png'),
        name:'新闻广播',
        urlId:'01'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-02.png'),
        name:'经济广播',
        urlId:'02'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-03.png'),
        name:'交通广播',
        urlId:'03'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-04.png'),
        name:'娱乐976·戏曲广播',
        urlId:'04'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-05.png'),
        name:'魅力881·戏音乐广播',
        urlId:'05'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-06.png'),
        name:'农村广播',
        urlId:'06'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-07.png'),
        name:'My Radio·影视广播',
        urlId:'07'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-08.png'),
        name:'私家车999·旅游广播',
        urlId:'08'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-09.png'),
        name:'UpRadio1066·教育广播',
        urlId:'09'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-10.png'),
        name:'乐龄1056·信息广播',
        urlId:'10'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-11.png'),
        name:'天籁936·古典音乐广播',
        urlId:'11'
    },
]

const HNTV_LOGO = [
    {
        url:require('logos/hntv-icon/icon-hntv-01.png'),
        name:'卫星频道',
        urlId:'01'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-02.png'),
        name:'都市频道',
        urlId:'02'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-03.png'),
        name:'民生频道',
        urlId:'03'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-04.png'),
        name:'法治频道',
        urlId:'04'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-05.png'),
        name:'电视剧频道',
        urlId:'05'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-06.png'),
        name:'新闻频道',
        urlId:'06'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-07.png'),
        name:'欢腾购物频道',
        urlId:'07'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-08.png'),
        name:'公共频道',
        urlId:'08'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-09.png'),
        name:'新农村频道',
        urlId:'09'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-10.png'),
        name:'国际频道',
        urlId:'10'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-11.png'),
        name:'航空港卫视频道',
        urlId:'11'
    },
]


const QRCODELIST = [
    [
        {
            url:require('qrcodes/hndt/01.png')
        },
        {
            url:require('qrcodes/hndt/02.png')
        },
        {
            url:require('qrcodes/hndt/03.png')
        },
        {
            url:require('qrcodes/hndt/04.png')
        },
        {
            url:require('qrcodes/hndt/05.png')
        },
        {
            url:require('qrcodes/hndt/06.png')
        },
        {
            url:require('qrcodes/hndt/07.png')
        },
        {
            url:require('qrcodes/hndt/08.png')
        },
        {
            url:require('qrcodes/hndt/09.png')
        },
        {
            url:require('qrcodes/hndt/10.png')
        },
        {
            url:require('qrcodes/hndt/11.png')
        },
    ],
    [
        {
            url:require('qrcodes/hntv/01.png')
        },
        {
            url:require('qrcodes/hntv/02.png')
        },
        {
            url:require('qrcodes/hntv/03.png')
        },
        {
            url:require('qrcodes/hntv/04.png')
        },
        {
            url:require('qrcodes/hntv/05.png')
        },
        {
            url:require('qrcodes/hntv/06.png')
        },
        {
            url:require('qrcodes/hntv/07.png')
        },
        {
            url:require('qrcodes/hntv/08.png')
        },
        {
            url:require('qrcodes/hntv/09.png')
        },
        {
            url:require('qrcodes/hntv/10.png')
        },
        {
            url:require('qrcodes/hntv/11.png')
        },
    ]
]



export {
    HNDT_LOGO,
    HNTV_LOGO,
    QRCODELIST
}