const HNDT_LOGO = [
    {
        url:require('logos/hndt-icon/icon-hndt-01.png'),
        name:'新闻广播',
        urlId:'01'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-02.png'),
        name:'经济广播',
        urlId:'02'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-03.png'),
        name:'交通广播',
        urlId:'03'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-04.png'),
        name:'娱乐976·戏曲广播',
        urlId:'04'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-05.png'),
        name:'魅力881·戏音乐广播',
        urlId:'05'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-06.png'),
        name:'农村广播',
        urlId:'06'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-07.png'),
        name:'My Radio·影视广播',
        urlId:'07'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-08.png'),
        name:'私家车999·旅游广播',
        urlId:'08'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-09.png'),
        name:'UpRadio1066·教育广播',
        urlId:'09'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-10.png'),
        name:'乐龄1056·信息广播',
        urlId:'10'
    },
    {
        url:require('logos/hndt-icon/icon-hndt-11.png'),
        name:'天籁936·古典音乐广播',
        urlId:'11'
    },
]

const HNTV_LOGO = [
    {
        url:require('logos/hntv-icon/icon-hntv-01.png'),
        name:'卫星频道',
        urlId:'01'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-02.png'),
        name:'都市频道',
        urlId:'02'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-03.png'),
        name:'民生频道',
        urlId:'03'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-04.png'),
        name:'法制频道',
        urlId:'04'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-05.png'),
        name:'电视剧频道',
        urlId:'05'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-06.png'),
        name:'新闻频道',
        urlId:'06'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-07.png'),
        name:'欢腾购物频道',
        urlId:'07'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-08.png'),
        name:'公共频道',
        urlId:'08'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-09.png'),
        name:'新农村频道',
        urlId:'09'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-10.png'),
        name:'国际频道',
        urlId:'10'
    },
    {
        url:require('logos/hntv-icon/icon-hntv-11.png'),
        name:'航空港卫视频道',
        urlId:'11'
    },
]


const WEIBOLINK = [
    [
        {
            url:'https://m.weibo.cn/p/1005051688864597'
        },
        {
            url:'https://m.weibo.cn/p/1005052137096053'
        },
        {
            url:'https://m.weibo.cn/p/1005051732802301'
        },
        {
            url:'https://m.weibo.cn/p/1005051934336047'
        },
        {
            url:'https://m.weibo.cn/p/1005051663884750'
        },
        {
            url:'https://m.weibo.cn/p/1005052144180455'
        },
        {
            url:'https://m.weibo.cn/p/1005051646080864'
        },
        {
            url:'https://m.weibo.cn/p/1005052773591493'
        },
        {
            url:'https://m.weibo.cn/p/1005052005817001'
        },
        {
            url:'https://weibo.com/60301056?refer_flag=1001030101_&is_hot=1'
        },
        {
            url:'https://m.weibo.cn/u/5662318247?refer_flag=1001030103_&refer_flag=1001030103_&jumpfrom=weibocom'
        }
    ],
    [
        {
            url:'https://m.weibo.cn/p/1005051834783273'
        },
        {
            url:'https://m.weibo.cn/p/1005051630423295'
        },
        {
            url:'https://m.weibo.cn/p/1005051769216315'
        },
        {
            url:'https://m.weibo.cn/p/1005051710226151'
        },
        {
            url:'https://m.weibo.cn/p/1005051714269484'
        },
        {
            url:'https://m.weibo.cn/p/1005053214879741'
        },
        {
            url:'https://m.weibo.cn/p/1005052928860467'
        },
        {
            url:'https://m.weibo.cn/p/1005052029700693'
        },
        {
            url:'https://m.weibo.cn/p/1005051294472663'
        },
        {
            url:'https://m.weibo.cn/u/3867204506?refer_flag=1001030101_&refer_flag=1001030101_&jumpfrom=weibocom'
        },
        {
            url:'https://m.weibo.cn/p/1005055680268344'
        }
    ]
]

const HTTVLIVELINK = [
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=135'
    },
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=136'
    },
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=137'
    },
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=138'
    },
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=139'
    },
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=140'
    },
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=141'
    },
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=142'
    },
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=143'
    },
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=144'
    },
    {
        url:'http://www.hntv.tv/live/zhibo.shtml?channel_id=146'
    }
]

export {
    HNDT_LOGO,
    HNTV_LOGO,    
    WEIBOLINK,
    HTTVLIVELINK
}